### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [userhiren/oh-my-zsh-gideon-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

**Comment by userhiren** [comment]
Joe (@unixorn) great suggestion. I have added in a quick screenshot along with installation instructions to help folks get started as fast a possible with importing and using it. Also thanks for helping to promote this in your plugins repository.

**Comment by unixorn** [comment]
Added in https://github.com/unixorn/awesome-zsh-plugins/pull/701
